name: Claude Code Workflow

on:
  workflow_dispatch:
    inputs:
      user_request:
        description: 'User Request'
        required: true
        default: 'Please enter your request here.'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install
          npm install -g @anthropic-ai/claude-code

      - name: Generate Documents and Implement
        env:
          USER_REQUEST: ${{ github.event.inputs.user_request }}
        run: |
          npm run generate
      
      - name: Get commit author info
        id: author
        run: |
          echo "name=$(git log -1 --pretty=format:'%an')" >> $GITHUB_OUTPUT
          echo "email=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_OUTPUT
      
      - name: Commit and Push Changes
        run: |
          git config --local user.email "${{ steps.author.outputs.email }}"
          git config --local user.name "${{ steps.author.outputs.name }}"
          git add .
          git commit -m "Auto-generated: Requirements, Design, Tasks, and Code" || echo "No changes to commit"
          git push
